services:
  - type: web
    name: sms-backend
    runtime: python3
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend/main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: MONGODB_URL
        value: mongodb+srv://bsse1320_db_user:FHwoFbjV1kfU8scs@cluster0.85gerfy.mongodb.net/?retryWrites=true&w=majority&ssl=true
      - key: DATABASE_NAME
        value: sms_app
      - key: SECRET_KEY
        value: bigbang-exam-care-super-secret-jwt-key-2024-production-ready
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ADMIN_EMAIL
        value: admin@gmail.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: ADMIN_FULL_NAME
        value: System Administrator
      - key: SMS_API_KEY
        value: mkY5eL3P0qEkxYh3yn92
      - key: SMS_API_URL
        value: http://bulksmsbd.net/api/smsapi
      - key: SMS_SENDER_ID
        value: 8809617624071
      - key: SMS_DRY_RUN
        value: false
      - key: CORS_ORIGINS
        value: https://royalsms.vercel.app,https://royalsms-git-main-mdmostafizurrahaman1s-projects.vercel.app,https://royal-272j67xmq-mdmostafizurrahaman1s-projects.vercel.app

  - type: web
    name: sms-frontend
    runtime: node
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "cd frontend && npm start"
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://sms-8kiu.onrender.com